### ISSUE TITLE
Broken link to terms and conditions

### ISSUE THREAD

**Issue by MaryBethBaker** [canada-ca/devex#46]
Hi team,

I noticed that the terms links on opportunities are broken.

![cookies](https://user-images.githubusercontent.com/532766/34895244-c2592f74-f7dc-11e7-9cc3-54a341a01569.png)

Thanks,

Mary Beth

**Comment by markwooff** [comment]
Huh, it appears that file was removed? The file (https://github.com/canada-ca/devex/blob/master/GCDevExchange_-_Terms_and_Conditions.pdf) used to exist in the repo.

@RachelMuston any ideas?

**Comment by RachelMuston** [comment]
Yes, this is my fault... based on feedback from the first opportunity, I converted the terms and conditions to an .md file so that people could easily track any changes made to it.
https://github.com/canada-ca/devex/blob/master/GCDevEx_TermsandConditions.md

Sorry @markwooff.  I forgot that we link to this file in a lot of places within the application.  It is going to take a lot of work to fix those broken links?

**Comment by markwooff** [comment]
No worries! Just fixed the 6 references to that file in the code. Closing issue.
