### ISSUE TITLE
Follow button does not appear on the french opportunity page

### ISSUE THREAD

**Issue by RachelMuston** [canada-ca/devex#48]
Hi @markwooff .  Was just writing up a tweet to let everyone know about the "follow" feature when I noticed that it does not seem to appear on the French opportunity. Do you get the same?

Here is what it I see on the English screen:
![follow_button_image](https://user-images.githubusercontent.com/29108013/35123741-85ca62b4-fc71-11e7-822c-78b16742f558.PNG)

and here is what I see on the French screen:
![follow_button_image_fre](https://user-images.githubusercontent.com/29108013/35123788-a9c317d8-fc71-11e7-987c-e294a43ef370.PNG)

**Comment by markwooff** [comment]
Yes this is also what I see @RachelMuston and it's due to the different domain that's being used for the French site. A user has to be logged in & have an email address in their profile to see the "Follow" button.

We had discussed that GitHub would need separate app configs for different domains but right now the login only works on the English side. We could always revert to having the /en and /fr routes on a single domain so that the GitHub login works in both languages.

**Comment by markwooff** [comment]
Follow button now appears on both English & French pages after domain was switched. Closing issue.
